"""Add subscription fields to User model

Revision ID: 10cbb240bc52
Revises: 6d73c1503386
Create Date: 2025-03-11 00:52:00.220438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cbb240bc52'
down_revision = '6d73c1503386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_end_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ### 