"""Add user profile fields

Revision ID: 6d73c1503386
Revises: 8d4a35b0a704
Create Date: 2025-03-11 00:31:43.621560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d73c1503386'
down_revision = '8d4a35b0a704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('operation_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('operation_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'state')
    op.drop_column('users', 'operation_type')
    op.drop_column('users', 'operation_name')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ### 